server:
  port: 8501

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  data:
    neo4j:
      username: neo4j
      password: password
      uri: neo4j://localhost:7687

  application:
    name: user-service

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration